const drinks = [
  {
    idDrink: "17222",
    strDrink: "A1",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: "vingt",
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
    strInstructionsES:
      "Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.",
    strInstructionsDE:
      "Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Grand Marnier",
    strIngredient3: "Lemon Juice",
    strIngredient4: "Grenadine",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 3/4 shot ",
    strMeasure2: "1 Shot ",
    strMeasure3: "1/4 Shot",
    strMeasure4: "1/8 Shot",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 21:42:09",
  },
  {
    idDrink: "13501",
    strDrink: "ABC",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Shot",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Shot glass",
    strInstructions: "Layered in a shot glass.",
    strInstructionsES: "Coloque todos los ingredientes en un vaso de chupito.",
    strInstructionsDE: "Schichtaufbau in einem Schnapsglas.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg",
    strIngredient1: "Amaretto",
    strIngredient2: "Baileys irish cream",
    strIngredient3: "Cognac",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/3 ",
    strMeasure2: "1/3 ",
    strMeasure3: "1/3 ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:32:08",
  },
  {
    idDrink: "17225",
    strDrink: "Ace",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Martini Glass",
    strInstructions:
      "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
    strInstructionsES:
      "Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.",
    strInstructionsDE:
      "Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Grenadine",
    strIngredient3: "Heavy cream",
    strIngredient4: "Milk",
    strIngredient5: "Egg White",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 shots ",
    strMeasure2: "1/2 shot ",
    strMeasure3: "1/2 shot ",
    strMeasure4: "1/2 shot",
    strMeasure5: "1/2 Fresh",
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 22:05:06",
  },
  {
    idDrink: "14610",
    strDrink: "ACID",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Shot",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Shot glass",
    strInstructions:
      "Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.",
    strInstructionsES:
      "Vierta primero el Bacardi 151, seguido del Wild Turkey 101 y sirva con Coca-Cola o Dr Pepper.",
    strInstructionsDE:
      "Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg",
    strIngredient1: "151 proof rum",
    strIngredient2: "Wild Turkey",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz Bacardi ",
    strMeasure2: "1 oz ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-11-15 11:28:37",
  },
  {
    idDrink: "17837",
    strDrink: "Adam",
    strDrinkAlternate: null,
    strTags: "Alcoholic,Holiday",
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
    strInstructionsES:
      "Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.",
    strInstructionsDE:
      "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg",
    strIngredient1: "Dark rum",
    strIngredient2: "Lemon juice",
    strIngredient3: "Grenadine",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "1 tsp ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "Yes",
    dateModified: "2016-09-02 11:29:29",
  },
  {
    idDrink: "13938",
    strDrink: "AT&T",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball Glass",
    strInstructions: "Pour Vodka and Gin over ice, add Tonic and Stir",
    strInstructionsES:
      "Vierta el vodka y la ginebra sobre el hielo, agregue la tónica y revuelva.",
    strInstructionsDE:
      "Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare la vodka e il gin sul ghiaccio, aggiungere l'acqua tonica e mescolare",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg",
    strIngredient1: "Absolut Vodka",
    strIngredient2: "Gin",
    strIngredient3: "Tonic water",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "4 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-04-24 22:00:19",
  },
  {
    idDrink: "17833",
    strDrink: "A. J.",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake ingredients with ice, strain into a cocktail glass, and serve.",
    strInstructionsES:
      "Agite bien los ingredientes con hielo, cuélelos en una copa de cóctel y sirva.",
    strInstructionsDE: null,
    strInstructionsFR: null,
    strInstructionsIT:
      "Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg",
    strIngredient1: "Applejack",
    strIngredient2: "Grapefruit juice",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "Yes",
    dateModified: "2016-09-02 11:16:58",
  },
  {
    idDrink: "17254",
    strDrink: "Bijou",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions: "Stir in mixing glass with ice and strain\r\n",
    strInstructionsES: null,
    strInstructionsDE: "In Mischglas mit Eis verrühren und abseihen.",
    strInstructionsFR: null,
    strInstructionsIT: "Mescolare nel mixing glass con ghiaccio e filtrare",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Green Chartreuse",
    strIngredient3: "Orange Bitters",
    strIngredient4: "Sweet Vermouth",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 dash",
    strMeasure2: "1 oz",
    strMeasure3: "1 oz",
    strMeasure4: "1 oz",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-12-19 18:09:45",
  },
  {
    idDrink: "11149",
    strDrink: "Boxcar",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Whiskey sour glass",
    strInstructions:
      "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Sour Glas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Filtrare in un bicchiere sour.Agitare bene.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Triple sec",
    strIngredient3: "Lemon juice",
    strIngredient4: "Grenadine",
    strIngredient5: "Egg white",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "1 tsp ",
    strMeasure4: "1/2 tsp ",
    strMeasure5: "1 ",
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-02 16:32:57",
  },
];

export default drinks;
